apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-nginx
  labels:
    app: udagram-nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: udagram-nginx
  template:
    metadata:
      labels:
        app: udagram-nginx
    spec:
      containers:
      - name: udagram-nginx
        image: grandia3/udagram-nginx
        ports:
        - containerPort: 80